### ISSUE TITLE
Demo env replies a 413 with big files then 1MB

### ISSUE THREAD

**Issue by gbc921** [josecolella/BusinessUnits-TreeVisualization#11]
Jose, with attachments bigger then 1MB I am getting a 413 - Request Entity Too Large response:

![image](https://user-images.githubusercontent.com/942648/29283962-4bfff820-80ff-11e7-842e-5d49b56a765c.png)

This is probably due to a low value (or no settings) regarding `client_max_body_size` property on `http` section of `nginx.conf`. Take a look [here](http://cnedelcu.blogspot.com.br/2013/09/nginx-error-413-request-entity-too-large.html).

**Comment by josecolella** [comment]
Thanks @gbc921. This is a regressive bug. I had set the param but after adding SSL, I forgot to add it back in. Commit https://github.com/josecolella/BusinessUnits-TreeVisualization/commit/1469335b9ceb28362470a4470bf6d0fc34d447fb closes #11
