### ISSUE TITLE
Make Layout Responsive

### ISSUE THREAD

**Issue by gbc921** [josecolella/BusinessUnits-TreeVisualization#2]
Current layout is not responsive enough. Decreasing window width hides text box info and no scroll bar is added. See screenshot below as a illustration.

![image](https://user-images.githubusercontent.com/942648/29045548-506979c8-7b9a-11e7-8b65-11add433ea0e.png)

**Comment by josecolella** [comment]
Thanks @gbc921. I will add this to my TODO for the project

**Comment by gbc921** [comment]
Also this changes should be reflected after uploading a file as well. Sometimes having a big application name or too many steps makes them hide behind the divs. Take a look:

![image](https://user-images.githubusercontent.com/942648/29128845-605af598-7cfb-11e7-9e42-63ff95c73eb2.png)

I would suggest to let the svg image div be relative to the applications one, and be able to freely expand to the right, even though a scroll bar might appear.
Also, It would be awesome if this div could scroll down together with the screen, so you don't select an application that is in the lower section and have to scroll up to see the image again.
