### ISSUE TITLE
Use a DNS Address instead of IP

### ISSUE THREAD

**Issue by gbc921** [josecolella/BusinessUnits-TreeVisualization#3]
You are using an IP address for accessing the website. There is a good (ad)free DNS service that you can use straight away to solve this:

https://www.duckdns.org/

Also, there are scripts ready-to-go to automatically update the IP as (if) needed.

What do you think!?

**Comment by josecolella** [comment]
@gbc921, Thanks for the suggestion. That was very easy to use. I will update the URL shown in the project. kudos mate.

**Comment by josecolella** [comment]
https://github.com/josecolella/BusinessUnits-TreeVisualization/commit/6c9e4b9aec7061482aaf250fdf9e84029c033a7f closes #3

**Comment by gbc921** [comment]
Jose, when uploading a file using the DNS address, nginx is returning 502:

![image](https://user-images.githubusercontent.com/942648/29075671-7cb31a40-7c29-11e7-8cd0-836772b10a81.png)
