### ISSUE TITLE
Use https instead of http in demo env

### ISSUE THREAD

**Issue by gbc921** [josecolella/BusinessUnits-TreeVisualization#4]
Would be awesome to use https in your demo environment with [Let's Encrypt](https://letsencrypt.org/) certificate!

**Comment by josecolella** [comment]
This is a great idea @gbc921. I have been able to generate the certificate, I just need to integrate into the existing docker pipeline. :neckbeard:

**Comment by josecolella** [comment]
Commit https://github.com/josecolella/BusinessUnits-TreeVisualization/commit/a4c39621003d686f684aea29338abe3968c3c9ee closes #4
